-- phpMyAdmin SQL Dump
-- version 4.9.0.1
-- https://www.phpmyadmin.net/
--
-- Servidor: sql303.infinityfree.com
-- Tiempo de generación: 27-02-2026 a las 17:19:05
-- Versión del servidor: 11.4.10-MariaDB
-- Versión de PHP: 7.2.22

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `if0_40977702_music`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `productos`
--

CREATE TABLE `productos` (
  `id` int(11) NOT NULL,
  `titulo` varchar(100) NOT NULL,
  `categoria` varchar(50) NOT NULL,
  `descripcion` text DEFAULT NULL,
  `imagen_url` varchar(255) DEFAULT NULL,
  `audio_url` varchar(255) DEFAULT NULL,
  `tamano` varchar(20) DEFAULT NULL,
  `link_descarga` varchar(255) DEFAULT NULL,
  `fecha_subida` datetime DEFAULT current_timestamp()
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

--
-- Volcado de datos para la tabla `productos`
--

INSERT INTO `productos` (`id`, `titulo`, `categoria`, `descripcion`, `imagen_url`, `audio_url`, `tamano`, `link_descarga`, `fecha_subida`) VALUES
(8, 'Keyzone Classic', 'Pianos', 'Keyzone Classic es un sample basado en:\r\n\r\n    Piano from Keyzone 1.\r\n    Yamaha Grand Piano.\r\n    Steinway Grand Piano.\r\n    Basic Electric Piano.\r\n    Rhodes Piano.\r\n', '../uploads/6977ac18478c0_img_keyzone.png', '', NULL, 'https://plugins4free.com/plugin/2848/', '2026-01-26 10:02:00'),
(4, 'GR-8 Synth', 'Synth', 'GR-8 es un sintetizador analógico virtual de 8 voces con efectos incorporados y un arpegiador.\r\n\r\nCaracterísticas:\r\n\r\n - Arpeggiator : 5 Modos (Arriba, Abajo, Alt 1, Alt 2, Aleatorio), 4 Octaves Range.\r\n - Modos de voz: Mono, Unison (8 voces), Chord (4 notas estéreo), Poly (8 voces).\r\n - Efectos de voz: Deslizado, Legato, Desatún de voz, Estéreo de voz extendido.\r\n - Osciladores : OSC 1 (Tri, Sierra, Pulso, Cuadrado), OSC 2 (Seno, Sierra, Pulso, Ruido).\r\n - Efectos del oscilador: Modulación cruzada (FM), Modulación de ancho de pulso        (PWM), Sincronización.\r\n- Filtros : Paso alto no resonante, paso bajo resonante (12, 18 o 24 dB/octava).\r\n- Modulación : Ganadora de paso, Rueda Mod, LFO, 2 Sobres.\r\n- EffectsEfectos: EQ, Distorsión, Phaser, Coro/Flanger, Retardo, Reverberación.\r\n- Presets : 128.\r\n', 'https://static.kvraudio.com/i/b/gr-8-synth2x.1733660429.jpg', '', NULL, 'https://www.kvraudio.com/product/gr-8-by-phuturetone', '2026-01-26 08:23:10'),
(3, 'MI GOZO BARAK - SECUENCIA', 'Secuencias', 'Secuencia con todo el Multitrack en formato .wav\r\nSe puede utilizar en cualquier daw', 'https://i.ytimg.com/vi/IxD3JiOo9DY/sddefault.jpg?v=63536d8c', 'https://youtu.be/IxD3JiOo9DY?si=M3X99ehGUYGx-Za-', NULL, 'https://drive.google.com/drive/folders/1MJTVH6Ede3eKWfQIGtylRRv0Iy-zw5J2', '2026-01-24 13:51:22'),
(5, 'Piano One', 'Pianos', 'Piano One, el modelado híbrido gratuito Concierto de Yamaha Grand.\r\n\r\nEl sonido del piano One proviene de la grand de conciertos Yamaha C7, un verdadero caballo de batalla en el mundo del piano profesional, que aparece en famosos escenarios de conciertos, en competiciones internacionales y en prestigiosos eventos musicales de todo el mundo.', '../uploads/69779c14d7011_img_piano1.png', '', '414 MB', 'https://plugins4free.com/plugin/1100/', '2026-01-26 08:53:40'),
(6, 'MT Power Drum Kit 2', 'Drums', 'MT Power Drum Kit 2 se lanzó en 2012, pero recientemente se convirtió en freeware. Es un plugin gratuito para batería acústica con mezclador integrado y una colección de grooves que puedes usar para crear canciones.\r\n\r\nPersonalmente no suena como bateria grabada en studio pero me suele recordar a baterias comprimidas de los 80\'s', '../uploads/69779ebb15933_img_mt-power-drum-kit-free.jpg', '', NULL, 'https://www.powerdrumkit.com/download76187.php', '2026-01-26 09:04:58'),
(7, 'Medley Alabanzas - Joel Batz', 'Secuencias', 'Secuencia con multitrack \r\nLink de descarga es directo de Google drive\r\nContiene:\r\n- Bass\r\n- Click\r\n- Drums\r\n- GTR\r\n- Guide\r\n- Keys\r\n- Lead\r\n- Synths\r\n- Brass', 'https://i.ytimg.com/vi/d95cewrKp0U/maxresdefault.jpg', '', NULL, 'https://drive.google.com/drive/folders/1Mc8f9G33qd3wNYVIwIQtqLq2FB4UzP1I', '2026-01-26 09:31:58'),
(9, 'DPiano-A', 'Pianos', 'piano eléctrico con preajustes poco duros, pero se pueden suavizar fácilmente, y sus volúmenes deben ser rechazados por su GUI muy intuitiva. Lo superpuse con DDX10 Digital FM Synthesizer de Dead Duck Software', '../uploads/6977af91e0205_img_piano.webp', '', NULL, 'https://plugins4free.com/plugin/2812/', '2026-01-26 10:16:49'),
(10, 'Vital - Matt Tytel', 'Synth', 'Matt Tytel ha lanzado Vital , un sintetizador de tabla de ondas de deformación espectral gratuito en formatos de complemento VST , VST3, AU y LV2 para estaciones de trabajo de audio digital en Windows, macOS y Linux.\r\n\r\nVital está disponible en cuatro ediciones con diferentes precios:\r\n\r\n    Vital Basic – Gratis\r\n    Vital Plus – $25\r\n    Vital Pro – $80\r\n    Suscripción Vital – $5 al mes\r\n\r\nLa funcionalidad principal es la misma en las cuatro ediciones de Vital. Esto significa que puedes crear los mismos sonidos con Vital Basic (gratis) y Vital Pro (80 $).', '../uploads/6977b3125f163_img_vital-synthesizer-1200x703.png', '', '', 'https://vital.audio/', '2026-01-26 10:31:46'),
(11, 'Ambient Reverb 4.0', 'FX / Plugins', 'El Reverberbio Ambiental es un Reverberación algorítmica.\r\n\r\nEstá destinado en primer lugar para la operación con material de sonido en un género ambiental, aunque con éxito se puede aplicar también en otros estilos musicales y las direcciones.\r\n\r\nLa característica distintiva de este plug-in es el amplio rango de tiempo de reverberación (hasta 100 segundos) que permite recibir tipos de reverberación, diferentes caracteres, y también una oportunidad en un sentido literal para congelar sonidos, al mismo tiempo para recibir almohadillas de sonido interesantes, como Frippertronics. El reverberador de Ambient Rever» funciona por el principio de la reverberación algorítmica con el cálculo de suficientes reflejos de sonido en el tiempo, permitiendo recibir una reverberación realista sin efecto de granularidad.\r\n\r\n    16 preajustes de fábrica.\r\n    Ecualizador paramétrico de 2 bandas.\r\n    Indicador y botones del nivel de entrada/salida.\r\n    Carga baja de la CPU/FPU.\r\n', 'https://media.plugins4free.com/img/Ambient-Reverb_2.jpg', '', NULL, 'https://plugins4free.com/plugin/2870/', '2026-01-26 10:35:37'),
(12, 'Dexed VST 0.9.6 Windows', 'Synth', 'Si está buscando un plugin de sintetizador VST tan bueno como DX7, Dexed VST Synth viene con 32 presets de fábrica gratuitos, definitivamente un gran plugin VST para agregar a la biblioteca de su productor.\r\n\r\nDexed VST es muy único, viene con 32 algoritmos diferentes que generarán 32 salidas diferentes de 1 sonido.', 'https://musictech.com/wp-content/uploads/2019/10/FM-synthesis-basics-DX7-plug-in-Dexed@2000x1500.jpg', '', NULL, 'https://www.producersbuzz.com/download/dexed-vst-0-9-6-windows/#unlock', '2026-01-26 10:59:55'),
(13, 'Steven Slate Batería Gratis', 'Drums', 'El VST gratuito de Steven Slate cumple a la perfección. Suena increíblemente sólido y realista, ofrece 3 presets listos para mezclar y permite la máxima personalización de tus sonidos. Con esta batería, estás listo para cualquier género musical.', '../uploads/6977be70dff4c_img_ssd_5_free_-_drum_kit_acoustic_1024x1024.jpg', '', NULL, 'https://stevenslatedrums.com/ssd5/', '2026-01-26 11:20:16'),
(14, 'Yamaha s90 Es (Kontakt)', 'Pianos', 'Piano versátil del famoso Yamaha s90\r\nSonidos realistas y ligeros soportados por cualquier pc\r\nNota: Requieres kontakt versión mínima 6 para hacerlo funcionar', 'https://i.ytimg.com/vi/Zf4ks2F1-hU/hq720.jpg?sqp=-oaymwE7CK4FEIIDSFryq4qpAy0IARUAAAAAGAElAADIQj0AgKJD8AEB-AHUBoAC4AOKAgwIABABGHIgOChGMA8=&rs=AOn4CLCHc3QgcHcKRhN1knC9wUDp_5wj0w', '', NULL, 'https://drive.google.com/file/d/1gjBC6OEfRgqP6vzx3G3A8Q8ofauhEsqh/view?usp=drive_link', '2026-01-26 11:50:02'),
(15, 'Nord Stage Organs (Kontakt)', 'Pianos', 'Libreria para kontatk de organos\r\nLink directo a google drive ', 'uploads/6977d097d67ed_img_upscalemedia-transformed.webp', '', NULL, 'https://drive.google.com/file/d/13bf5P1zz2eQsUkgqyCeAoabX83P0-qrQ/view?usp=drive_link', '2026-01-26 12:00:14'),
(16, 'PG-8X 2.0', 'Synth', 'Toda su magia se encuentra en el emulador gratuito (PG8X). Ofrece controles muy intuitivos: puedes crear rápidamente sonidos de los 80 y parches analógicos modernos. Además, carga los archivos \"Sysex\" originales del JX-8P, así que tienes un montón de parches para descargar.\r\n\r\nUno de los sintetizadores gratuitos más geniales de todos, perfecto para pistas synthwave.\r\n\r\nDisponible para Mac OS y Windows', '../uploads/6977e07814d9b_img_unnamed.png', '', NULL, 'https://sites.google.com/site/mlvst0/', '2026-01-26 13:45:28'),
(17, 'TAL-NoiseMaker', 'Synth', 'Los desarrolladores de TAL, famosos por su emulación del Juno-60, también ofrecen un sintetizador gratuito inspirado en Juno llamado Noisemaker. Su diseño es muy similar al del Juno y ofrece desde potentes bajos hasta relajantes pads analógicos. Incluye el característico Chorus de dos modos de Juno para un efecto de máxima intensidad.\r\n\r\n', '../uploads/6977e2088dd23_img_tal-noisemaker-new2_2048x2048.webp', '', NULL, 'https://tal-software.com/products/tal-noisemaker', '2026-01-26 13:52:08'),
(18, 'Yamaha Motif XS8 (Kontakt)', 'Pianos', 'Sample para Kontakt del Piano Yamaha Motif XS8\r\n', '../uploads/6977e52ce6fca_img_preview.jpg', '', NULL, 'https://mega.nz/file/Zv9FXRoT#z24-3W3Ang3LgQNxmupA7YLXtB3e3uvQMBf6Y06b9Bk', '2026-01-26 14:05:32'),
(19, 'DSK Brass', 'Brass', '\r\n\r\nCaracterísticas y descarga:\r\n\r\n– 2 capas, 23 instrumentos que incluyen:\r\nSax Soprano, Sax Tenor, Sax Alto, Harmon Mute,\r\nTrompeta, Trompeta Mudo, Trompeta Staccato,\r\nOleaje de trompeta, Trompeta de Piccolo, Trombón,\r\nTrombone Cup Mute, Trombón Wah Mute, Tuba,\r\nTuba Staccato, Cuerno Flugel, Cuerno Francés,\r\nMudo De Cuerno Francés, Conjunto De Latón...\r\n\r\n– Octave select y micro-detuner\r\n– Efectos (Retardo, flanger)\r\n– Automatización Midi', 'https://i.ytimg.com/vi/qolY9GD6nvU/hq720.jpg?sqp=-oaymwE7CK4FEIIDSFryq4qpAy0IARUAAAAAGAElAADIQj0AgKJD8AEB-AH0CYAC0AWKAgwIABABGF0gXShdMA8=&rs=AOn4CLCa6eQvKAZMIM_PWmW4LNCQBUwiog', '', NULL, 'https://www.dskmusic.com/dsk-brass/', '2026-01-26 14:29:40'),
(20, 'MJUC jr Compressor', 'FX / Plugins', 'Es un diseño variable-mu** con mucho ambiente. capaz de nivelación suave pero también efectos de bombeo pesado. Con sus dos etapas de ganancia y simulación de transformador entre etapas, ofrece un escenario de sonido muy profundo y animado.\r\nEl conmutador de temporización de tres posiciones no solo controla los tiempos de ataque y liberación de la unidad, sino también la velocidad de giro de los transformadores y la temporización de las otras partes de la circuitería, que influyen directamente en los armónicos generados (saturación).\r\n\r\nMJUC jr. es una mezcla de Mk1 y Mk2 de su hermano mayor MJUC. Está combinando características de compresión muy naturales y densas de los primeros días de este tipo de compresión con un enfoque de sonido más avanzado y más armónicos creando las composiciones variables de los años sesenta. “', '../uploads/6977eb9169840_img_MJUC.jpg', '', NULL, 'https://www.audiopluginsforfree.com/mjuc-jr/', '2026-01-26 14:32:49'),
(21, 'Korg M1', 'Pianos', 'Contraseña del archivo: 123\r\nKORG Collection - M1 V2 es una recreación virtual (VST/AU/AAX) del icónico sintetizador workstation de 1988, famoso por sus sonidos PCM de alta calidad que definieron la música house y pop de los 90. Esta versión digital incluye más de 3,300 sonidos, abarcando todas las tarjetas ROM originales, con filtros mejorados y una interfaz moderna escalable para producciones actuales. \r\nEste video ofrece una reseña profunda del VST KORG M1:\r\nCaracterísticas Principales del Korg M1 VST:\r\n\r\n  - Sonidos Legendarios: Incluye el icónico \"M1 Piano\", órganos, pads, y cuerdas originales.\r\n  - Contenido Completo: Recrea el M1 original, la expansión M1EX y las 19 tarjetas ROM opcionales.\r\n  - Multitímbrico: 8 partes, ideal para producción en estudio.\r\n  - Efectos: Dos efectos de inserción por parte y dos maestros, totalizando 18 efectos simultáneos.\r\n  - Interfaz Moderna: Navegador de sonidos mejorado, funciones de búsqueda por categoría y soporte para alta resolución (4K/Retina). \r\n\r\nEl VST es parte de la KORG Collection y también se ofrece en versiones limitadas (como M1 Le) junto con controladores Korg. \r\n', '../uploads/6978fc54706d2_img_Korg-M1-review-featured-image-1200x1200-1.jpg', '', NULL, 'https://drive.google.com/file/d/1PdlxIF7ytz6Rc075rA2-AX-KlCcfCk2q/view?usp=sharing', '2026-01-27 09:56:36'),
(22, 'Abstract Crystal Pads', 'Synth', 'Abstract Crystal Pads es una colección de 30 almohadillas abstractas para su banda sonora de película, banda sonora ambiental o su nuevo proyecto de la nueva era! Cada sonido es libre de regalías y se puede utilizar en proyectos comerciales y no comerciales.', '../uploads/697a9455c15a3_img_CrystalPAds.jpg', '', NULL, 'https://samplescience.gumroad.com/l/abstractcrystalpads', '2026-01-28 14:57:25'),
(23, 'KONTAKT 7.8.1', 'Software', 'Kontatk es  un lanzador de samples para controladores midi', 'uploads/699e1d3cc309a_img_Kontakt 7 (1).png', '', '', 'https://www.mediafire.com/file/22lwh8i17e86fst/Kontakt.v7.8.1_Win.rar/file', '2026-02-24 13:45:57'),
(24, 'KONTAKT 6.1', 'Software', 'Programa kontakt full para windows', '../uploads/699e1ce13c611_img_NI_Kontakt_6_Windows.jpg', '', '', 'https://mega.nz/file/6J5GFYLZ#ulhus9mZkwIWex0Vl8gznn8nk9rxwM8lI6l1BajLg9M', '2026-02-24 13:49:20'),
(25, 'Korg Triton synth', 'Pianos', 'El KORG Triton Studio VST es la variante más potente de la serie TRITON, e incorpora válvulas “Valve Force” por primera vez en una estación de trabajo musical, así como la mayoría de las nuevas formas de onda de las series PCM y ExB-PCM. El robusto sonido analógico de las válvulas se combina con software para lograr un rendimiento sonoro asombroso.', '../uploads/699e1dcccc8ab_img_3fdccd7fcb8df913376d9de1ffd267c7_sp.jpg', '', '262 MB', 'https://mega.nz/file/AXwUxKIY#DnLzFLN2z_Li-3WzAl-2ICbRXBY_5uY0CKLWrxcduwg', '2026-02-24 13:53:16'),
(26, 'KEYSCAPE 1.6.0', 'Pianos', 'Keyscape es un instrumento virtual desarrollado por Spectrasonics que ofrece una de las colecciones más completas de teclados digitales y acústicos raros y coleccionables del mundo. Este instrumento virtual incluye más de 500 sonidos de 36 modelos de teclado, desde pianos acústicos hasta pianos eléctricos, y es compatible con Mac y PC en formatos como AAX, VST y AU. Los sonidos están grabados con una calidad excepcional.\r\n\r\n', 'uploads/699e3c9f81a5e_img_1000295248.png', '', '', 'magnet:?xt=urn:btih:856AB56E3AC92A33AEEFF63C2192E1783F41516F&tr=http%3A%2F%2Fbt2.t-ru.org%2Fann%3Fmagnet&dn=Spectrasonics%20-%20Keyscape%20Patch%20Library%201.6.0c%20update%20WIN%2FOSX%20(OMNISPHERE)', '2026-02-24 14:33:01'),
(28, 'KEYSCAPE CORE LIBRARY', 'Pianos', 'Keyscape es un instrumento virtual desarrollado por Spectrasonics que ofrece una de las colecciones más completas de teclados digitales y acústicos raros y coleccionables del mundo. Este instrumento virtual incluye más de 500 sonidos de 36 modelos de teclado, desde pianos acústicos hasta pianos eléctricos, y es compatible con Mac y PC en formatos como AAX, VST y AU. Los sonidos están grabados con una calidad excepcional, ', 'uploads/699e3cc00845c_img_1000295248.png', '', '', 'magnet:?xt=urn:btih:92AD2705FC514E6E1631F7F0C7226C613857459D&tr=http%3A%2F%2Fbt4.t-ru.org%2Fann%3Fmagnet&dn=Spectrasonics%20-%20Keyscape%201.3%20Factory%20Library%20%5BSTEAM%5D%20%5B23.09.2022%5D', '2026-02-24 14:34:02'),
(29, 'Ableton midi controller', 'Software', 'Software desarrollado por Moises Valencia para controlar canales de ableton live, asignando cualquier ajuste midi que quieras a los botones existentes', '../uploads/699f2c35f2b68_img_Captura de pantalla 2026-02-25 110628.png', '', '45.4 MB', 'https://drive.google.com/file/d/1FLkGfl0xx2RWE27ArhQWLReOhkeN2j9R/view?usp=sharing', '2026-02-25 09:07:01'),
(30, 'Ableton live lite 12', 'Software', 'Ableton Live 12 Lite es una manera nueva y fácil de escribir, grabar, producir e interpretar tus propias canciones. Viene con muchos productos de hardware de forma gratuita.', '../uploads/699f4481cf251_img_focusrite-live-12-ableton-upgrade-news-2400x1350.jpg', '', '3.1 GB', 'https://www.ableton.com/es/products/live-lite/', '2026-02-25 10:50:41'),
(31, 'SYNTHAGE 1.4v (Kontakt)', 'Pianos', 'Esta es una biblioteca desarrollada por Júnior Porciúncula [Brasil]. Su objetivo es ofrecer a los usuarios la máxima calidad. Por lo tanto, es imposible saber la diferencia de sonido entre Synthage y Yamaha Montage para quienes no tienen el dinero suficiente para comprar un teclado real. Toda la base se basa en Yamaha Montage; todos los sonidos son de Yamaha Montage.', '../uploads/699f45fa57c0c_img_maxresdefault-2020-08-29T101914.449.webp', '', '9.7 GB', 'magnet:?xt=urn:btih:UKFFHMJJIPL426Q4FRRTG6STQCHYQUGL&dn=SYNTHAGE%201.4&tr=https%3A%2F%2Fonly-soft.org%2Fbt%2Fannounce.php%3Fuk%3DvKGSXxAZUF', '2026-02-25 10:56:57'),
(32, 'Compact Stage Pianos (Kontakt)', 'Pianos', '27 tones in the PIANO module.\r\n5 Grand – 2 Upright – 2 CP80 – 18 DX\r\n\r\n29 tones in the E-PIANO module\r\n5 odhes – 3 Wurlitzer – 3 Clavi – 18 DX\r\n\r\n33 tones in the SUB module\r\n8 Pads – 10 Organs – 7 Chromatic Percussion – 8 Others', '../uploads/699f46ddcaeca_img_COMPACT-STAGE-PIANOS.webp', '', '8.4 GB', 'magnet:?xt=urn:btih:0F650648B20E0D19FACDC23461648A53175D8AB0&tr=http%3A%2F%2Fbt.t-ru.org%2Fann%3Fmagnet&dn=Junior%20Porciuncula%20%E2%80%93%20Compact%20Stage%20Piano%20(KONTAKT)', '2026-02-25 11:00:45'),
(33, 'Korg W-10 (Kontakt)', 'Synth', 'Biblioteca basada en Korg 01/W. Creada por Junior Porciuncula.\r\nSuperperilla para combinar módulos. Gestor de memoria para reducir el consumo de memoria. El script está optimizado para reducir el consumo de procesador.', '../uploads/699f477e786b6_img_Junior-Porciuncula-W10-for-Kontakt.webp', '', '', 'https://drive.google.com/file/d/1a2-3GCkDYqHwhEKZNmaOkIAb_acrkZFw/view?usp=sharing', '2026-02-25 11:03:26'),
(34, 'Valhalla DSPs', 'Secuencias', 'Efecto de Reverberación para pianos, voces o guitarras ', '../uploads/699f48c7cfc08_img_26.jpg', '', '13 MB', 'magnet:?xt=urn:btih:4282823A7814407C5C2A64EA4E3387FB125FC73D&tr=http%3A%2F%2Fbt.t-ru.org%2Fann%3Fmagnet&dn=ValhallaDSP%20-%20ValhallaDSP%20bundle%202025.11%20-%20VST%2C%20VST3%2C%20AAX%20x64%20%5B15.11.2025%5D(VR)', '2026-02-25 11:08:55'),
(36, 'Ultimate Stage Pianos (Kontakt) ', 'Pianos', 'Emulador del nord stage para kontakt, sonidos profesionales para tocar en vivo', 'uploads/699f638d73c77_img_Web_Photo_Editor (1).jpg', '', '6.5 GB', 'magnet:?xt=urn:btih:8D330C6AE3AD8E597F45680CD499B65705B410A5&tr=http%3A%2F%2Fbt3.t-ru.org%2Fann%3Fmagnet&dn=J%C3%BAnior%20Porci%C3%BAncula%20-%20Ultimate%20Stage%20Pianos%20HD%20(KONTAKT)', '2026-02-25 13:02:30'),
(37, 'Rhodes Affair ', 'Pianos', '“The Case of Rhodes” es un instrumento muy específico. Para algunos, podría ser simplemente otro sonido de parto, pero para otros, ¡es justo lo que siempre han buscado! “The Case of Rhodes” no podría ser más simple ni más directo. ¡Contiene un solo sonido!\r\n\r\nEsta es una réplica fiel y precisa del sonido Rhodes de Robbie Buchanan de los 90; un sonido que te resultará más que familiar al escuchar la música de Luis Miguel, Pocahontas (Disney), Cathy Troccoli, From A Distance, etc.\r\nEn colaboración con el productor y teclista Urs Wiesendanger, desarrollamos esta maravillosa nueva incorporación a la familia Audiolounge.', '../uploads/69a0971a21182_img_1522699973.webp', '', '3.2 GB', 'magnet:?xt=urn:btih:AA31E643B8BC586C2FBCB3638D4630334FEFBF05&tr=http%3A%2F%2Fbt2.t-ru.org%2Fann%3Fmagnet&dn=Audiolounge%20Urs%20Wiesendanger%20-%20Rhodes%20Affair%202.4.2.0%20VSTi%20x86%20x64%20%5B12.07.2018%5D', '2026-02-26 10:55:22'),
(38, 'Synthogy – Ivory Grand Pianos II (KONTAKT)', 'Pianos', 'La colección de pianos virtuales más popular del mundo, diseñada para el sampler NI Kontakt (versión 5.03 o posterior).\r\n\r\nLa colección de pianos de cola virtuales más popular del mundo ha mejorado con la creación de Ivory II-Grand Pianos. Con un conjunto de sonidos enormemente ampliado, con casi el doble de capas de velocidad, y el motor DSP de piano Ivory II mejorado con Modelado de Resonancia Armónica para una auténtica Vibración Simpática de Cuerdas, Ivory II-Grand Pianos alcanza los niveles más altos de tecnología de muestreo y síntesis.', '../uploads/69a0981baac08_img_ivory.jpg', '', '2.8 GB', 'magnet:?xt=urn:btih:E7FC06742492FB390FACB4C80B4397BD3BA7DE45&tr=http%3A%2F%2Fbt4.t-ru.org%2Fann%3Fmagnet&dn=Synthogy%20-%20Ivory%20Grand%20Pianos%20II%20(KONTAKT)', '2026-02-26 10:59:39'),
(39, 'Amazound – Acoustic Pianos (KONTAKT)', 'Secuencias', 'Si busca pianos acústicos fáciles de cargar, rápidos de tocar y fáciles de usar, ha elegido la opción correcta.\r\nEsta colección contiene un conjunto de samples de alta calidad, especialmente programados para Kontakt. Todos los instrumentos están multimuestreados con un sonido estéreo nítido de 24 bits (también disponible en versión de 16 bits). Más de 1 GB de datos de audio, incluyendo pianos de cola Steinway, Yamaha, Bosendorfer y otros. El conjunto también incluye samples de piano de sintetizadores famosos como el Korg Triton y el Roland XP80.', 'uploads/69a09b3a60e1b_img_Web_Photo_Editor.jpg', '', '1.8 GB', 'magnet:?xt=urn:btih:6ED1DAD64F62FF88D8418F49960D7E3FE7E4A449&tr=http%3A%2F%2Fbt.t-ru.org%2Fann%3Fmagnet&dn=Amazound%20-%20Acoustic%20Pianos%20(Kontakt)', '2026-02-26 11:10:23'),
(40, 'K90-Stage Pianos (Kontakt)', 'Pianos', 'Creado por la brasileña Kaique muniz Teclista, productora musical y arreglista\r\nGran selección de pianos y pads acústicos eléctricos.\r\nmuestra del tercer piso 3, yamaha s90 es y pads de ambas llaves\r\nlibrería y renunciar a las funciones principales que lo dejarán sin palabras cuando las use en su configuración, cargándose de manera rápida y fácil de usar\r\nInterfaz de control sencilla y pianos de alta presencia y muy ligeros\r\nprueba en computadoras de gama baja si soy muy bueno\r\ny la nitidez sigue el ritmo de muchas librerías de pianos actuales\r\nAsí que cargue el escenario K90 ahora en su estudio y experimente la comodidad de tonos buenos y poco procesados.', '../uploads/69a09fb7020f3_img_KA-90.jpg', '', '7.1 GB', 'magnet:?xt=urn:btih:F2BF23EFF6D557CEADDA048D912113332E7E451C&tr=http%3A%2F%2Fbt.t-ru.org%2Fann%3Fmagnet&dn=K-Instruments%20-%20K90%20Stage%20(KONTAKT)', '2026-02-26 11:32:06'),
(41, 'Ample Bass P Lite', 'Software', 'Bajo acustico convertido en digital para actuarlo desde un controlador midi ', '../uploads/69a0bb277b977_img_abpl01.jpg', '', '203.6 MB', 'https://drive.google.com/file/d/1IojwMuXOldisMyS_JlbPmEZiTTEXjQuI/view?usp=sharing', '2026-02-26 13:29:11'),
(42, 'Ample Guitar M Lite', 'Software', 'Ample guitar es un instrumento virtual capacitado en simular una guitarra acustica', '../uploads/69a0bbd2a7b39_img_agml01.jpg', '', '270.4 GB', 'https://drive.google.com/file/d/160nJqPrqyFlOiXHm01IKi1JpZmPOnSmr/view?usp=sharing', '2026-02-26 13:32:03'),
(43, 'TDR NOVA EQ', 'FX / Plugins', 'TDR Nova es un ecualizador dinámico paralelo de alto nivel, disponible como plugin VST gratuito (y en versión paga) desarrollado por Tokyo Dawn Records. Combina la estructura de un ecualizador paramétrico clásico con potentes capacidades de compresión multibanda, permitiendo ajustar la ganancia de frecuencias específicas solo cuando superan un umbral definido.', '../uploads/69a1c3e5e3407_img_Seite-1-Kopie-1-1.png', '', '8.3 MB', 'https://www.tokyodawn.net/tdr-nova/', '2026-02-27 08:18:45'),
(44, 'Xfer OTT ', 'FX / Plugins', 'OTT es un complemento de compresor gratuito Over The Top de tres bandas de Xfer Records, que comenzó como un ajuste preestablecido para el complemento Multiband Dynamics en Ableton Live. Vale la pena echarle un vistazo si quieres algo que esté a la altura del nombre del complemento.', 'https://delivery.pixelbin.io/predictions/outputs/1d/sr/upscaleRestricted/019c9ffc-ab1c-7883-988f-3ae368b5589d/result_0.webp', '', '2 MB', 'https://plugins4free.com/plugin/1224/', '2026-02-27 08:46:52');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `productos`
--
ALTER TABLE `productos`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `productos`
--
ALTER TABLE `productos`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=45;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
